Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824741): Gdk-CRITICAL **: 08:46:58.268: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824793): Gdk-CRITICAL **: 08:46:58.996: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824609): Gdk-CRITICAL **: 08:46:59.183: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823936): Gdk-CRITICAL **: 08:46:59.185: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823871): Gdk-CRITICAL **: 08:46:59.698: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823463): Gdk-CRITICAL **: 08:47:00.864: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823922): Gdk-CRITICAL **: 08:47:01.251: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825174): Gdk-CRITICAL **: 08:47:01.359: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825147): Gdk-CRITICAL **: 08:47:02.094: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825188): Gdk-CRITICAL **: 08:47:02.994: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825059): Gdk-CRITICAL **: 08:47:03.051: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824973): Gdk-CRITICAL **: 08:47:10.226: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824941): Gdk-CRITICAL **: 08:47:10.715: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824272): Gdk-CRITICAL **: 08:47:10.861: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824380): Gdk-CRITICAL **: 08:47:10.907: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824823): Gdk-CRITICAL **: 08:47:10.961: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824712): Gdk-CRITICAL **: 08:47:11.069: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824916): Gdk-CRITICAL **: 08:47:11.255: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825221): Gdk-CRITICAL **: 08:47:12.513: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824179): Gdk-CRITICAL **: 08:47:12.969: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824504): Gdk-CRITICAL **: 08:47:12.970: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824158): Gdk-CRITICAL **: 08:47:13.159: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823519): Gdk-CRITICAL **: 08:47:14.197: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825222): Gdk-CRITICAL **: 08:47:13.700: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824584): Gdk-CRITICAL **: 08:47:14.190: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823687): Gdk-CRITICAL **: 08:47:14.145: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823379): Gdk-CRITICAL **: 08:47:14.140: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824992): Gdk-CRITICAL **: 08:47:14.154: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824833): Gdk-CRITICAL **: 08:47:14.529: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824248): Gdk-CRITICAL **: 08:47:14.647: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824192): Gdk-CRITICAL **: 08:47:14.600: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823828): Gdk-CRITICAL **: 08:47:15.111: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825102): Gdk-CRITICAL **: 08:47:15.181: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823597): Gdk-CRITICAL **: 08:47:15.558: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824480): Gdk-CRITICAL **: 08:47:19.040: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823671): Gdk-CRITICAL **: 08:47:19.260: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825037): Gdk-CRITICAL **: 08:47:19.320: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824965): Gdk-CRITICAL **: 08:47:19.435: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824080): Gdk-CRITICAL **: 08:47:19.625: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824036): Gdk-CRITICAL **: 08:47:19.704: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824132): Gdk-CRITICAL **: 08:47:23.078: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823456): Gdk-CRITICAL **: 08:47:23.085: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824365): Gdk-CRITICAL **: 08:47:23.092: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825158): Gdk-CRITICAL **: 08:47:23.186: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824400): Gdk-CRITICAL **: 08:47:23.189: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823437): Gdk-CRITICAL **: 08:47:23.193: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823470): Gdk-CRITICAL **: 08:47:23.197: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824849): Gdk-CRITICAL **: 08:47:23.201: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823426): Gdk-CRITICAL **: 08:47:23.204: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824312): Gdk-CRITICAL **: 08:47:23.209: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824534): Gdk-CRITICAL **: 08:47:23.213: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824349): Gdk-CRITICAL **: 08:47:23.217: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823624): Gdk-CRITICAL **: 08:47:23.221: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824763): Gdk-CRITICAL **: 08:47:23.225: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824542): Gdk-CRITICAL **: 08:47:23.229: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823905): Gdk-CRITICAL **: 08:47:23.231: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824230): Gdk-CRITICAL **: 08:47:23.237: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823549): Gdk-CRITICAL **: 08:47:23.241: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824410): Gdk-CRITICAL **: 08:47:23.261: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823410): Gdk-CRITICAL **: 08:47:23.265: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824678): Gdk-CRITICAL **: 08:47:23.269: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824548): Gdk-CRITICAL **: 08:47:23.275: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824328): Gdk-CRITICAL **: 08:47:23.281: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824576): Gdk-CRITICAL **: 08:47:23.290: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823638): Gdk-CRITICAL **: 08:47:23.301: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824018): Gdk-CRITICAL **: 08:47:23.305: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823854): Gdk-CRITICAL **: 08:47:23.309: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823363): Gdk-CRITICAL **: 08:47:23.316: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824473): Gdk-CRITICAL **: 08:47:23.325: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824882): Gdk-CRITICAL **: 08:47:23.330: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824563): Gdk-CRITICAL **: 08:47:23.337: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824750): Gdk-CRITICAL **: 08:47:23.345: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823779): Gdk-CRITICAL **: 08:47:23.349: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825180): Gdk-CRITICAL **: 08:47:23.353: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825165): Gdk-CRITICAL **: 08:47:23.357: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824116): Gdk-CRITICAL **: 08:47:23.361: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823981): Gdk-CRITICAL **: 08:47:23.365: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825152): Gdk-CRITICAL **: 08:47:23.369: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824005): Gdk-CRITICAL **: 08:47:23.373: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825213): Gdk-CRITICAL **: 08:47:23.377: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824064): Gdk-CRITICAL **: 08:47:23.381: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824876): Gdk-CRITICAL **: 08:47:23.385: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823395): Gdk-CRITICAL **: 08:47:23.389: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823484): Gdk-CRITICAL **: 08:47:23.409: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823750): Gdk-CRITICAL **: 08:47:23.417: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825088): Gdk-CRITICAL **: 08:47:23.425: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824701): Gdk-CRITICAL **: 08:47:23.469: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823580): Gdk-CRITICAL **: 08:47:23.473: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824146): Gdk-CRITICAL **: 08:47:23.477: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824925): Gdk-CRITICAL **: 08:47:23.493: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823708): Gdk-CRITICAL **: 08:47:23.497: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824952): Gdk-CRITICAL **: 08:47:23.501: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823612): Gdk-CRITICAL **: 08:47:23.505: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823447): Gdk-CRITICAL **: 08:47:23.517: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823658): Gdk-CRITICAL **: 08:47:23.525: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824770): Gdk-CRITICAL **: 08:47:23.553: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823810): Gdk-CRITICAL **: 08:47:23.561: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823500): Gdk-CRITICAL **: 08:47:23.613: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825131): Gdk-CRITICAL **: 08:47:23.789: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824240): Gdk-CRITICAL **: 08:47:23.801: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..Initalising...
Running Sim...
..Initalising...
Running Sim...
.Initalising...
Running Sim...
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[8268 1916]
....
[1780 8399]
.....
[8370 1818]
.
[1742 8448]
.............
[1723 8490]
.....
[8503 1702]
..................................
[8828 1328]
....
[1737 8465]
.
[1797 8408]
.
[1953 8256]
......
[7938 2323]
.
[8519 1657]
.
[8080 2164]
.
[2189 8077]
....
[8457 1743]
.
[2817 7503]
.
[8921 1248]
.
[8837 1304]
..
[2573 7723]
.
[8704 1463]
..
[7995 2284]
.
[8315 1887]
.
[8721 1422]
.
[9076 1052]
.
[8412 1795]
.
[8765 1394]
.
[8227 1993]
.
[8838 1322]
.
[9142  972]
.
[9099 1014]
.
[8264 1952]
.
[8982 1148]
.
[8832 1316]
.
[2767 7531]
.
[2993 7353]
.
[9145  963]
.
[8319 1873]
.
[9067 1040]
.
[9067 1040]
.
[9147  980]
.
[6502 3869]
.
[8370 1802]
.
[8970 1149]
.
[3753 6599]
..
[8791 1353]
.
[9185  931]
..
[9065 1065]
.
[8507 1659]
.
[8371 1827]
.
[8128 2079]
..
[6892 3413]
.
[8492 1670]
..
[3370 6976]
.
[3716 6590]
....
[3811 6581]
.
[7487 2792]
...
[5268 5123]
.
[3382 6949]
.
[8318 1873]
.
[7149 3141]
.
[6157 4188]
..
[5320 5041]
....
[7257 3045]
.
[3682 6626]
.
[5689 4700]
.
[4852 5532]
....
[6064 4304]
..
[5311 5064]
.
[6481 3851]
..
[7379 2876]
.
[4714 5674]
......
[7145 3125]
.......
[6718 3551]
.....
[4676 5680]
.......
[5665 4688]
..
[4981 5333]
.........
[5606 4788]
...................................................................................................................................................................................................
Data Dump...
.............
Data Dump...

Data Dump...
..
Data Dump...
.....
Data Dump...
.....
Data Dump...
.......................
Data Dump...
.................
Data Dump...
............................................................................................................................................................
[  56 1962]
..............
[1827    3]
....
[  64 2014]
............
[1912    6]
...................
[2031    8]
.
[2034    9]
..
[2066   14]
..
[1952    8]
.........
[2041    6]
..........
Data Dump...
.
Data Dump...
........
[2027   10]
........................
Data Dump...
..
Data Dump...
..
[2130   11]
.....
[ 101 2190]
........
[2146    8]
....
[2180    2]
................
[2192   11]
.
[2094   32]
...
Data Dump...
...
[2216   12]
...
Data Dump...

[2175   41]
.....
[2155   33]
..
Data Dump...
.....
[2160   61]
.........
[2236   13]
....
[2235   13]
..
Data Dump...
....
Data Dump...
......
[ 186 2075]
.
[2064  285]
.
[2043  205]
.....
[2201   70]
..
[2227   13]
.
Data Dump...
.................
[2136   90]
.........
[ 240 2294]
....
[2191  110]
......
[2237   58]
...
[2174   72]
.......
[ 287 2135]
..
[2180   85]
..
[2160  204]
.....
Data Dump...
..........
[2225   33]
........
[2248   41]
.
[ 283 2203]
....
[ 335 2188]
.
Data Dump...
.
Data Dump...
......
[2248   31]
......................
[2178   94]
...
Data Dump...
...
Data Dump...
..
[2247   53]
.....
Data Dump...
.........................
[1998  317]
.....
[ 493 2007]
...
Data Dump...
.......
Data Dump...
...
Data Dump...
..
[ 595 1863]
..
[1581  846]
...........
Data Dump...
....
Data Dump...
.
[1978  371]
.
[ 507 1891]
...
Data Dump...

[2057  256]
..
[1861  454]
.
[ 697 1721]
.
[2094  184]
............
[1576  756]
...
[ 850 1258]
...
Data Dump...
..
[1241 1173]
.
Data Dump...

Data Dump...

Data Dump...
.
[1156 1250]
.
Data Dump...
..
[1072 1370]
.
[2078  180]
..
[1742  554]
.....
[1636  715]
..
[ 741 1477]
.
[1282 1096]
....
[1310 1147]
.
[1869  429]
.....
[1008 1442]
............
[1638  595]
.
Data Dump...
..........
[1344  789]
..
Data Dump...
..
[1148 1195]
...
Data Dump...
.......
[1359 1008]
.......
Data Dump...
...
Data Dump...
.........
Data Dump...
.......
Data Dump...
.
Data Dump...
.......
Data Dump...
.......
Data Dump...
..
Data Dump...
.
Data Dump...
..................
Data Dump...
.................
Data Dump...
....................
Data Dump...
....
Data Dump...
....
Data Dump...
......................
Data Dump...

Data Dump...
..............
Data Dump...
..............
Data Dump...
.
Data Dump...

Data Dump...
...
Data Dump...
...
Data Dump...
........
Data Dump...

Data Dump...

Data Dump...
......
Data Dump...
......
Data Dump...

Data Dump...
..
Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...
.........
Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...
No 1 8
Done
slurmstepd-phcompute025: error: Detected 19 oom-kill event(s) in StepId=824563.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
