Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066405): Gdk-CRITICAL **: 08:47:34.468: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066718): Gdk-CRITICAL **: 08:47:34.480: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066708): Gdk-CRITICAL **: 08:47:38.763: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066023): Gdk-CRITICAL **: 08:47:39.371: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066529): Gdk-CRITICAL **: 08:47:39.379: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066413): Gdk-CRITICAL **: 08:47:39.437: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4065992): Gdk-CRITICAL **: 08:47:39.445: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066419): Gdk-CRITICAL **: 08:47:39.453: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066283): Gdk-CRITICAL **: 08:47:39.456: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066611): Gdk-CRITICAL **: 08:47:39.481: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066504): Gdk-CRITICAL **: 08:47:39.760: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066678): Gdk-CRITICAL **: 08:47:39.900: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066734): Gdk-CRITICAL **: 08:47:56.814: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066322): Gdk-CRITICAL **: 08:47:56.882: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066480): Gdk-CRITICAL **: 08:47:56.886: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066175): Gdk-CRITICAL **: 08:47:56.894: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066721): Gdk-CRITICAL **: 08:47:56.914: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066103): Gdk-CRITICAL **: 08:47:56.934: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066143): Gdk-CRITICAL **: 08:47:56.939: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066450): Gdk-CRITICAL **: 08:47:56.949: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066652): Gdk-CRITICAL **: 08:47:56.970: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066162): Gdk-CRITICAL **: 08:47:56.982: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066216): Gdk-CRITICAL **: 08:47:56.990: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066330): Gdk-CRITICAL **: 08:47:57.030: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066484): Gdk-CRITICAL **: 08:47:57.033: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066660): Gdk-CRITICAL **: 08:47:57.039: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066392): Gdk-CRITICAL **: 08:47:57.051: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066292): Gdk-CRITICAL **: 08:47:57.066: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066007): Gdk-CRITICAL **: 08:47:57.078: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066087): Gdk-CRITICAL **: 08:47:57.082: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066100): Gdk-CRITICAL **: 08:47:57.098: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066228): Gdk-CRITICAL **: 08:47:57.100: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066238): Gdk-CRITICAL **: 08:47:57.110: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066031): Gdk-CRITICAL **: 08:47:57.114: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066498): Gdk-CRITICAL **: 08:47:57.117: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066188): Gdk-CRITICAL **: 08:47:57.125: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4065984): Gdk-CRITICAL **: 08:47:57.129: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066130): Gdk-CRITICAL **: 08:47:57.134: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066552): Gdk-CRITICAL **: 08:47:57.137: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066446): Gdk-CRITICAL **: 08:47:57.142: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066628): Gdk-CRITICAL **: 08:47:57.148: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066388): Gdk-CRITICAL **: 08:47:57.153: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066472): Gdk-CRITICAL **: 08:47:57.158: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066037): Gdk-CRITICAL **: 08:47:57.169: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066666): Gdk-CRITICAL **: 08:47:57.177: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066725): Gdk-CRITICAL **: 08:47:57.180: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066236): Gdk-CRITICAL **: 08:47:57.189: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066120): Gdk-CRITICAL **: 08:47:57.375: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066374): Gdk-CRITICAL **: 08:47:57.379: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066624): Gdk-CRITICAL **: 08:47:57.383: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066266): Gdk-CRITICAL **: 08:47:57.388: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066185): Gdk-CRITICAL **: 08:47:57.392: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066166): Gdk-CRITICAL **: 08:47:57.399: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066366): Gdk-CRITICAL **: 08:47:57.403: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066397): Gdk-CRITICAL **: 08:47:57.407: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066288): Gdk-CRITICAL **: 08:47:57.428: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4065999): Gdk-CRITICAL **: 08:47:57.468: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066201): Gdk-CRITICAL **: 08:47:57.472: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066296): Gdk-CRITICAL **: 08:47:57.476: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066338): Gdk-CRITICAL **: 08:47:57.480: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066520): Gdk-CRITICAL **: 08:47:57.218: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066350): Gdk-CRITICAL **: 08:47:57.488: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066378): Gdk-CRITICAL **: 08:47:57.492: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066304): Gdk-CRITICAL **: 08:47:57.496: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066595): Gdk-CRITICAL **: 08:47:57.499: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066214): Gdk-CRITICAL **: 08:47:57.504: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066566): Gdk-CRITICAL **: 08:47:57.515: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066687): Gdk-CRITICAL **: 08:47:57.243: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066015): Gdk-CRITICAL **: 08:47:56.903: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066360): Gdk-CRITICAL **: 08:47:57.532: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4065978): Gdk-CRITICAL **: 08:47:57.247: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066691): Gdk-CRITICAL **: 08:47:57.539: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066558): Gdk-CRITICAL **: 08:47:57.552: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066613): Gdk-CRITICAL **: 08:47:57.556: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066713): Gdk-CRITICAL **: 08:47:57.564: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066512): Gdk-CRITICAL **: 08:47:57.567: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066247): Gdk-CRITICAL **: 08:47:57.576: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066256): Gdk-CRITICAL **: 08:47:57.580: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066542): Gdk-CRITICAL **: 08:47:57.583: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066458): Gdk-CRITICAL **: 08:47:57.588: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066454): Gdk-CRITICAL **: 08:47:57.640: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066730): Gdk-CRITICAL **: 08:47:57.286: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066630): Gdk-CRITICAL **: 08:47:57.655: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066598): Gdk-CRITICAL **: 08:47:57.660: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066580): Gdk-CRITICAL **: 08:47:57.663: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066494): Gdk-CRITICAL **: 08:47:57.666: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066059): Gdk-CRITICAL **: 08:47:57.672: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066206): Gdk-CRITICAL **: 08:47:57.676: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066738): Gdk-CRITICAL **: 08:47:57.680: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066081): Gdk-CRITICAL **: 08:47:57.301: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066196): Gdk-CRITICAL **: 08:47:57.311: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066741): Gdk-CRITICAL **: 08:47:57.312: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066534): Gdk-CRITICAL **: 08:47:57.727: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066546): Gdk-CRITICAL **: 08:47:57.732: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066055): Gdk-CRITICAL **: 08:47:57.744: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066076): Gdk-CRITICAL **: 08:47:57.748: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066315): Gdk-CRITICAL **: 08:47:57.751: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:4066138): Gdk-CRITICAL **: 08:47:57.326: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066716): Gdk-CRITICAL **: 08:47:57.776: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:4066683): Gdk-CRITICAL **: 08:47:57.847: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1693 8902]
.
[1769 8812]
...
[1742 8846]
.
[1710 8839]
......
[1707 8814]
.
[1814 8777]
.
[1721 8833]
.
[1672 8850]
.
[1867 8688]
.
[1776 8754]
.
[1749 8829]
..
[1770 8782]
..
[1745 8815]
.
[1735 8870]
.
[1692 8874]
..
[1795 8771]
.
[1813 8747]
.
[1751 8849]
.
[1957 8618]
.
[1755 8825]
.
[1858 8720]
.
[1726 8836]
.
[1692 8866]
.
[1751 8832]
.
[1962 8602]
.
[1820 8726]
.
[2040 8503]
.
[1816 8741]
.
[1758 8773]
.
[1737 8806]
.
[1797 8762]
.
[1697 8857]
.
[1774 8774]
.
[1694 8848]
.
[1757 8805]
.
[1775 8815]
.
[2178 8403]
.
[1732 8825]
.
[1796 8751]
.
[1730 8853]
.
[1739 8826]
.
[1731 8811]
.
[1705 8839]
.
[1884 8679]
.
[1798 8806]
.
[2117 8450]
.
[1833 8752]
.
[1814 8737]
.
[1736 8835]
.
[1698 8852]
.
[1765 8801]
.
[1819 8718]
.
[1813 8758]
.
[2431 8097]
..
[1724 8833]
..
[2261 8243]
.
[1727 8847]
...
[2292 8218]
.
[1960 8588]
.
[2069 8481]
.
[2624 7900]
.
[1706 8848]
.
[2667 7836]
.
[2449 8025]
...............
[3320 7187]
...
[3192 7368]
....
[3653 6924]
......
[3422 7025]
..........
[3863 6613]
...
[3169 7373]
....................
[3596 6869]
..
[4295 6246]
..
[4732 5708]
...............................................
[7561 2780]
............................................................................................................................................................................................................................
Data Dump...
......
Data Dump...

Data Dump...
.
Data Dump...
.........................
Data Dump...
..............
Data Dump...

Data Dump...
...........
Data Dump...
............................................................................................
[  49 3211]
...............
[  47 3136]
.....
[  48 3254]
..........
[  48 3143]
.....................
[  46 3052]
.
[  47 3112]
.......
[  60 3209]
......
[  62 3248]
..
[  56 3149]
.....
[  75 3190]
....................
[  83 2801]
....
[  69 3132]
.....
[  56 3160]
.
[  68 3038]
............
[  78 2997]
..
[  83 2908]
.
[  75 2999]
......
[  95 2914]
...........
[  79 3103]
....
[  84 2868]
........
[  83 2689]
....
[  89 2879]
.
[ 113 2503]
..
[  87 2896]
........
[ 102 3045]
....
[  94 2877]
.
[ 100 2762]
....
[ 122 2757]
....
[ 106 2921]
........
Data Dump...
.....
Data Dump...
............
[  78 3010]
......
[ 111 2980]
.....
[ 112 2920]
.....
Data Dump...
..................
[ 155 2796]
.
[ 197 2412]
........
Data Dump...
.............
Data Dump...
..
[ 159 2698]
...
[ 219 2473]
...
[ 169 2411]
....
Data Dump...
...............
[ 257 2425]
..
Data Dump...

[ 248 2121]
......
[ 268 2119]
....
Data Dump...
..
[ 251 2122]
...
[ 151 2769]
.
[ 214 2353]
...
Data Dump...

Data Dump...
..............
[ 309 2148]
....
[ 362 1753]
...............
[ 357 2284]
.
[ 319 1962]
.
[ 310 2319]
..............
Data Dump...
...
[ 318 1940]
.................
Data Dump...
.......
Data Dump...
.....
[ 433 2063]
........
Data Dump...
.
Data Dump...
....
[ 565 1736]
...........
Data Dump...
..
[ 527 1790]
.
[ 393 1843]
........................
Data Dump...
...
Data Dump...
...
Data Dump...
..
[ 548 2152]
....
[ 728 2062]
..........................
[ 743 1465]
......
[ 861 1158]
...
Data Dump...

[ 751 1198]
...
Data Dump...
...
Data Dump...

Data Dump...
.
Data Dump...
..
[ 907 1371]
.....
Data Dump...
....
[2426   71]
.
Data Dump...
.
[ 808 1608]
.
Data Dump...

Data Dump...
....
[1127 1132]
......
Data Dump...
..
[1173  846]
.........
[1038 1222]
....
Data Dump...

[1169 1339]
....
[1597  644]
.......
Data Dump...
......
Data Dump...
.........................
Data Dump...
..........................
Data Dump...
..
[34 99]

Data Dump...
..................
Data Dump...
............
[41 88]

Data Dump...
...
[32 70]

Data Dump...
...........
[31 83]

Data Dump...
............
[27 80]

Data Dump...
...
[38 48]

Data Dump...
......
[36 52]

Data Dump...
..
[36 41]

Data Dump...
.............
[46 96]

Data Dump...
......
[39 90]

Data Dump...

[42 74]

Data Dump...
........
[40 35]

Data Dump...
.
[44 20]
....
Data Dump...
......
[36 45]

Data Dump...
............
[50 84]
...
Data Dump...
...
[52 35]
...
[48 50]
....
Data Dump...

Data Dump...

[56 40]
.....
Data Dump...
...
[ 56 113]
.
Data Dump...
...
[ 67 122]
...
Data Dump...
..............
[60 31]
......
Data Dump...

[59 24]
.
[44 23]
...
[73 38]
..
Data Dump...

[69 43]
..
[106   5]
..
Data Dump...

Data Dump...

[66 41]
.
Data Dump...
.
Data Dump...

[71 17]
.
[66 34]
.
[78 59]
.
Data Dump...

[84 21]
.
Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...
Low 1 6
Done
slurmstepd-phcompute010: error: Detected 20 oom-kill event(s) in StepId=824571.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
