Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824672): Gdk-CRITICAL **: 08:46:58.343: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824222): Gdk-CRITICAL **: 08:46:59.086: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824072): Gdk-CRITICAL **: 08:46:59.200: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824510): Gdk-CRITICAL **: 08:46:59.216: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823782): Gdk-CRITICAL **: 08:46:59.524: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824800): Gdk-CRITICAL **: 08:46:59.557: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824089): Gdk-CRITICAL **: 08:47:01.319: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824636): Gdk-CRITICAL **: 08:47:01.381: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824895): Gdk-CRITICAL **: 08:47:01.763: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823856): Gdk-CRITICAL **: 08:47:02.585: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825196): Gdk-CRITICAL **: 08:47:03.875: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824147): Gdk-CRITICAL **: 08:47:03.880: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823709): Gdk-CRITICAL **: 08:47:03.884: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825175): Gdk-CRITICAL **: 08:47:03.902: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825226): Gdk-CRITICAL **: 08:47:03.909: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824346): Gdk-CRITICAL **: 08:47:03.917: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824601): Gdk-CRITICAL **: 08:47:03.945: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824587): Gdk-CRITICAL **: 08:47:04.057: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823890): Gdk-CRITICAL **: 08:47:04.133: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825109): Gdk-CRITICAL **: 08:47:04.365: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823711): Gdk-CRITICAL **: 08:47:04.390: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824108): Gdk-CRITICAL **: 08:47:04.449: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824311): Gdk-CRITICAL **: 08:47:04.462: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825127): Gdk-CRITICAL **: 08:47:04.558: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824813): Gdk-CRITICAL **: 08:47:04.616: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824171): Gdk-CRITICAL **: 08:47:10.692: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823715): Gdk-CRITICAL **: 08:47:10.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824232): Gdk-CRITICAL **: 08:47:11.788: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823851): Gdk-CRITICAL **: 08:47:12.053: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824182): Gdk-CRITICAL **: 08:47:14.990: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824474): Gdk-CRITICAL **: 08:47:27.412: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824789): Gdk-CRITICAL **: 08:47:27.445: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824316): Gdk-CRITICAL **: 08:47:27.849: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824486): Gdk-CRITICAL **: 08:47:27.909: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824874): Gdk-CRITICAL **: 08:47:28.917: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824538): Gdk-CRITICAL **: 08:47:29.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824456): Gdk-CRITICAL **: 08:47:30.697: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824774): Gdk-CRITICAL **: 08:47:30.749: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824684): Gdk-CRITICAL **: 08:47:30.753: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824440): Gdk-CRITICAL **: 08:47:30.757: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824828): Gdk-CRITICAL **: 08:47:30.769: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824777): Gdk-CRITICAL **: 08:47:30.781: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824008): Gdk-CRITICAL **: 08:47:30.794: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823735): Gdk-CRITICAL **: 08:47:31.025: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823933): Gdk-CRITICAL **: 08:47:31.041: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825078): Gdk-CRITICAL **: 08:47:31.063: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823948): Gdk-CRITICAL **: 08:47:31.069: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825211): Gdk-CRITICAL **: 08:47:31.073: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823713): Gdk-CRITICAL **: 08:47:31.077: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824910): Gdk-CRITICAL **: 08:47:31.109: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824388): Gdk-CRITICAL **: 08:47:31.125: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824052): Gdk-CRITICAL **: 08:47:31.136: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824844): Gdk-CRITICAL **: 08:47:31.141: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825223): Gdk-CRITICAL **: 08:47:31.157: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825123): Gdk-CRITICAL **: 08:47:31.161: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825216): Gdk-CRITICAL **: 08:47:31.173: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824137): Gdk-CRITICAL **: 08:47:31.189: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824122): Gdk-CRITICAL **: 08:47:31.201: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825154): Gdk-CRITICAL **: 08:47:31.209: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823797): Gdk-CRITICAL **: 08:47:31.369: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824418): Gdk-CRITICAL **: 08:47:31.373: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823844): Gdk-CRITICAL **: 08:47:31.377: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824837): Gdk-CRITICAL **: 08:47:31.390: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823965): Gdk-CRITICAL **: 08:47:31.433: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825224): Gdk-CRITICAL **: 08:47:31.441: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825219): Gdk-CRITICAL **: 08:47:31.469: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823808): Gdk-CRITICAL **: 08:47:31.473: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823769): Gdk-CRITICAL **: 08:47:31.517: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823914): Gdk-CRITICAL **: 08:47:31.527: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824676): Gdk-CRITICAL **: 08:47:31.657: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823817): Gdk-CRITICAL **: 08:47:31.697: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825119): Gdk-CRITICAL **: 08:47:31.917: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825182): Gdk-CRITICAL **: 08:47:32.014: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824250): Gdk-CRITICAL **: 08:47:32.034: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825168): Gdk-CRITICAL **: 08:47:32.037: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824374): Gdk-CRITICAL **: 08:47:32.053: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824200): Gdk-CRITICAL **: 08:47:32.073: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823731): Gdk-CRITICAL **: 08:47:32.083: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825138): Gdk-CRITICAL **: 08:47:32.105: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824666): Gdk-CRITICAL **: 08:47:32.109: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824527): Gdk-CRITICAL **: 08:47:32.145: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825042): Gdk-CRITICAL **: 08:47:32.149: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823872): Gdk-CRITICAL **: 08:47:32.165: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825187): Gdk-CRITICAL **: 08:47:32.178: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823717): Gdk-CRITICAL **: 08:47:32.186: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824856): Gdk-CRITICAL **: 08:47:32.205: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823787): Gdk-CRITICAL **: 08:47:32.209: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824260): Gdk-CRITICAL **: 08:47:32.213: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823759): Gdk-CRITICAL **: 08:47:32.237: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823834): Gdk-CRITICAL **: 08:47:32.240: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824032): Gdk-CRITICAL **: 08:47:32.289: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824284): Gdk-CRITICAL **: 08:47:32.313: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824618): Gdk-CRITICAL **: 08:47:32.321: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825201): Gdk-CRITICAL **: 08:47:32.337: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824556): Gdk-CRITICAL **: 08:47:32.361: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825052): Gdk-CRITICAL **: 08:47:32.393: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823737): Gdk-CRITICAL **: 08:47:32.443: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824498): Gdk-CRITICAL **: 08:47:32.461: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823739): Gdk-CRITICAL **: 08:47:32.637: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823721): Gdk-CRITICAL **: 08:47:32.737: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..Initalising...
Running Sim...
..Initalising...
Running Sim...
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[9165 1849]
..
[9213 1817]
..........
[1700 9220]
......
[1770 9192]
..............
[9270 1681]
.
[1745 9171]
.........
[1786 9219]
..
[1630 9282]
.
[9179 1871]
...
[9405 1372]
..........
[9503 1105]
.....
[9458 1213]
.
[9563  956]
....
[2052 8847]
....
[9365 1257]
.
[9269 1576]
.
[8622 2025]
.
[1787 9183]
.
[2193 8658]
..
[8819 2042]
.
[9339 1312]
.
[9515 1111]
.
[9048 1701]
.
[2448 8391]
..
[9486 1120]
.
[9292 1364]
.
[9525 1096]
.
[9544  994]
.
[8756 1933]
...
[9515 1033]
.
[9448 1060]
.
[9432 1149]
.
[9409 1272]
...
[9344 1238]
..
[9524  996]
.
[9447 1056]
..
[9566  933]
.
[9486 1052]
.
[8977 1746]
.
[3287 7509]
.
[9478 1154]
.
[8989 1571]
.
[7771 3050]
..
[9174 1393]
.
[2957 7911]
.
[3184 7711]
..
[8948 1685]
.
[3115 7717]
.
[8666 1934]
.
[8512 2152]
.
[9530 1020]
.
[8527 2103]
.
[8006 2694]
..
[3340 7448]
.
[8644 1971]
..
[4376 6379]
..
[7755 2925]
.
[3448 7429]
.
[3871 6959]
...
[7793 2896]
.....
[4460 6291]
..
[6210 4492]
..
[5064 5691]
.
[7721 3026]
.
[6279 4463]
.
[7783 2778]
...
[6563 4158]
.....
[5681 5119]
.
[6502 4157]
.
[5011 5691]
........
[5055 5743]
..
[6062 4675]
..............
[7635 3035]
.
[6844 3779]
...
[6800 3867]
.
[5646 5090]
...................................................................................................................................................................................................................
Data Dump...
.............
Data Dump...
..................
Data Dump...
...
Data Dump...
......
Data Dump...
...
Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...
...
Data Dump...
.....
Data Dump...
..........
Data Dump...
.........
Data Dump...
.............................................................................................................................................................................................
[4138   50]
.......
[4104    8]
...
[4092    7]
..........
[4002    7]
.....
[ 105 3953]
.............
[3951    9]
..............
[3752   23]
..
[3827   27]
..
[3762   11]
.
[3915    5]
.......
[3793   10]
.......
[3664   12]
..
[3848   19]
...
[3597   41]
..
[3620   16]
...........
[3534   10]
.
[3521   23]
...
[3616   15]
.......
[3492   34]
......
[ 212 3483]
.....
[3585   19]
...........
[3439   93]
.......
[ 226 3400]
..............
[3244  179]
........
[3385   29]
...
[3071  110]
...
[3217  115]
.....
[3227   90]
......
[3245   41]
............
[3256   66]
........
[3128   91]
.....................
[ 412 3018]
............
[3009  143]
.
[3004   94]
.
[ 462 2447]
....
[2900  144]
.
[ 436 2932]
...
[ 455 2901]
.......
[ 620 2469]
....
[2865  269]
.......
[2482  604]
.............
[2696  363]
..
[2750  181]
.
[2659  328]
.
[ 629 2449]
............
[ 589 2758]
......
[1045 1942]
..
[ 725 2503]
.......
[2625  446]
...............
[2122  786]
.
[1901 1012]
..
[2068  780]
......
[1823 1139]
..
[1461 1522]
.
[2322  458]
.
[1114 1845]
.......
[1352 1503]
......
[1533 1487]
..
[2573  430]
......
[2263  571]
......
[1211 1812]
.
[1755 1227]
...................
[1688 1211]
................................................................................
[239  23]
.................
[205   7]
.
[199   6]
..................
[245   3]
.
Data Dump...
..........
[ 35 287]
........................
Data Dump...

Data Dump...
..........
Data Dump...
...
[204   7]
.........
Data Dump...
.............
[229  13]
.....
[208   9]
...
[211   5]
...........
[196  11]
.
[210   5]
...........
Data Dump...
.........
[203   9]
...................
[191   9]
.
[191  12]
..
Data Dump...
...
[200   7]
.
Data Dump...
..
Data Dump...
....
Data Dump...
..
Data Dump...
.
[188   6]
............
[222  10]
..
[185  10]
.......
[ 55 250]
.....
Data Dump...
..................
Data Dump...
.
[188   8]
.
[169   7]
...
[ 45 296]
..
Data Dump...

Data Dump...
..........
[184  21]
............
Data Dump...
..............
Data Dump...
..
Data Dump...
.
Data Dump...
.............
[205  24]
.....
[191  21]
.
[164  36]
...
[166  16]
...
Data Dump...
...
Data Dump...
.....
Data Dump...
........
[175  19]
.....
Data Dump...
..
[173   9]
.............
[174  12]
..
[169  18]
.......
[ 63 230]
..................
[ 55 236]
...
Data Dump...

[ 61 248]
.
Data Dump...
..
Data Dump...
..
Data Dump...
...
[ 74 156]
.......
Data Dump...
.
[159  22]
....
[147  13]
.....
[75 82]
..
[144  15]
...........
Data Dump...

[129  86]
...
[151  34]
....
Data Dump...
..
[ 73 163]
.
Data Dump...

Data Dump...
.......
[139  41]
.
[149  22]
.
[ 95 128]
...
[ 70 229]
...
[155  21]
.
Data Dump...
..
[ 78 196]
....
Data Dump...
.........
Data Dump...
..
[163  53]
...
[140  60]
.
[118  81]
......
Data Dump...

Data Dump...

[111  99]
..
[113  50]
..
Data Dump...
.
[103  98]
..
[106  93]
...
Data Dump...
.
[116  98]
.
[142  25]
......
Data Dump...
..
Data Dump...
.......
Data Dump...
..
[ 93 134]
.
Data Dump...

[ 97 152]
..
[142  41]
...
[119 109]
..
[163  40]
..
Data Dump...

Data Dump...

Data Dump...
..
Data Dump...
...
Data Dump...

[101  88]
...............
Data Dump...
.
Data Dump...
...
Data Dump...
.
Data Dump...

Data Dump...

Data Dump...
.
Data Dump...
......
Data Dump...

Data Dump...
......
Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...
.
Data Dump...
No 1 4
Done
slurmstepd-phcompute025: error: Detected 17 oom-kill event(s) in StepId=824559.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
