Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825366): Gdk-CRITICAL **: 08:46:58.363: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825423): Gdk-CRITICAL **: 08:46:59.347: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825677): Gdk-CRITICAL **: 08:46:59.626: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825382): Gdk-CRITICAL **: 08:46:59.646: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825545): Gdk-CRITICAL **: 08:47:01.334: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825585): Gdk-CRITICAL **: 08:47:01.481: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825523): Gdk-CRITICAL **: 08:47:01.486: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825515): Gdk-CRITICAL **: 08:47:01.857: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825691): Gdk-CRITICAL **: 08:47:02.173: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825557): Gdk-CRITICAL **: 08:47:02.136: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825619): Gdk-CRITICAL **: 08:47:02.208: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825505): Gdk-CRITICAL **: 08:47:02.716: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825419): Gdk-CRITICAL **: 08:47:02.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825675): Gdk-CRITICAL **: 08:47:04.536: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825467): Gdk-CRITICAL **: 08:47:04.593: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825489): Gdk-CRITICAL **: 08:47:04.598: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825713): Gdk-CRITICAL **: 08:47:04.611: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825429): Gdk-CRITICAL **: 08:47:05.112: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825659): Gdk-CRITICAL **: 08:47:05.186: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825465): Gdk-CRITICAL **: 08:47:06.028: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825425): Gdk-CRITICAL **: 08:47:06.243: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825509): Gdk-CRITICAL **: 08:47:06.324: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825399): Gdk-CRITICAL **: 08:47:06.335: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825394): Gdk-CRITICAL **: 08:47:06.566: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825633): Gdk-CRITICAL **: 08:47:06.613: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825707): Gdk-CRITICAL **: 08:47:07.008: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825647): Gdk-CRITICAL **: 08:47:16.214: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825696): Gdk-CRITICAL **: 08:47:16.565: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825673): Gdk-CRITICAL **: 08:47:16.657: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825699): Gdk-CRITICAL **: 08:47:16.719: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825714): Gdk-CRITICAL **: 08:47:16.757: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825715): Gdk-CRITICAL **: 08:47:16.817: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825641): Gdk-CRITICAL **: 08:47:16.866: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825671): Gdk-CRITICAL **: 08:47:16.873: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825591): Gdk-CRITICAL **: 08:47:16.881: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825569): Gdk-CRITICAL **: 08:47:16.982: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825611): Gdk-CRITICAL **: 08:47:17.021: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825561): Gdk-CRITICAL **: 08:47:17.055: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825578): Gdk-CRITICAL **: 08:47:17.067: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825631): Gdk-CRITICAL **: 08:47:17.081: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825689): Gdk-CRITICAL **: 08:47:17.163: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825363): Gdk-CRITICAL **: 08:47:17.271: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825704): Gdk-CRITICAL **: 08:47:17.331: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825389): Gdk-CRITICAL **: 08:47:17.365: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825433): Gdk-CRITICAL **: 08:47:17.388: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825493): Gdk-CRITICAL **: 08:47:17.401: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825455): Gdk-CRITICAL **: 08:47:17.421: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825487): Gdk-CRITICAL **: 08:47:17.461: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825664): Gdk-CRITICAL **: 08:47:17.472: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825447): Gdk-CRITICAL **: 08:47:17.487: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825573): Gdk-CRITICAL **: 08:47:17.507: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825473): Gdk-CRITICAL **: 08:47:17.591: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825565): Gdk-CRITICAL **: 08:47:17.617: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825537): Gdk-CRITICAL **: 08:47:17.661: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825497): Gdk-CRITICAL **: 08:47:17.686: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825439): Gdk-CRITICAL **: 08:47:17.710: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825427): Gdk-CRITICAL **: 08:47:17.838: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825435): Gdk-CRITICAL **: 08:47:17.874: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825403): Gdk-CRITICAL **: 08:47:17.930: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825553): Gdk-CRITICAL **: 08:47:17.958: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825445): Gdk-CRITICAL **: 08:47:17.981: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825600): Gdk-CRITICAL **: 08:47:18.061: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825384): Gdk-CRITICAL **: 08:47:18.077: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825549): Gdk-CRITICAL **: 08:47:18.085: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825370): Gdk-CRITICAL **: 08:47:18.088: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825483): Gdk-CRITICAL **: 08:47:18.556: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825623): Gdk-CRITICAL **: 08:47:18.588: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825380): Gdk-CRITICAL **: 08:47:18.835: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825638): Gdk-CRITICAL **: 08:47:18.984: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825605): Gdk-CRITICAL **: 08:47:19.007: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825527): Gdk-CRITICAL **: 08:47:19.018: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825503): Gdk-CRITICAL **: 08:47:19.099: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825372): Gdk-CRITICAL **: 08:47:19.103: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825415): Gdk-CRITICAL **: 08:47:19.118: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825471): Gdk-CRITICAL **: 08:47:19.125: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825709): Gdk-CRITICAL **: 08:47:19.149: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825629): Gdk-CRITICAL **: 08:47:19.154: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825700): Gdk-CRITICAL **: 08:47:19.158: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825477): Gdk-CRITICAL **: 08:47:19.161: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825511): Gdk-CRITICAL **: 08:47:19.165: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825716): Gdk-CRITICAL **: 08:47:19.182: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825542): Gdk-CRITICAL **: 08:47:19.212: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825593): Gdk-CRITICAL **: 08:47:19.219: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825635): Gdk-CRITICAL **: 08:47:19.239: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825376): Gdk-CRITICAL **: 08:47:19.281: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825625): Gdk-CRITICAL **: 08:47:22.300: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825595): Gdk-CRITICAL **: 08:47:22.453: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825533): Gdk-CRITICAL **: 08:47:22.543: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825411): Gdk-CRITICAL **: 08:47:22.558: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825406): Gdk-CRITICAL **: 08:47:22.569: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825368): Gdk-CRITICAL **: 08:47:22.573: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825649): Gdk-CRITICAL **: 08:47:22.607: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825705): Gdk-CRITICAL **: 08:47:22.611: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825654): Gdk-CRITICAL **: 08:47:22.629: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825461): Gdk-CRITICAL **: 08:47:22.653: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825583): Gdk-CRITICAL **: 08:47:22.661: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825374): Gdk-CRITICAL **: 08:47:22.665: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825712): Gdk-CRITICAL **: 08:47:22.677: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825519): Gdk-CRITICAL **: 08:47:22.681: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825686): Gdk-CRITICAL **: 08:47:22.693: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...Initalising...
Running Sim...
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1726 9982]
...
[1709 9999]
.
[1718 9997]
.
[1739 9996]
.
[1676 9999]
.
[1771 9997]
.
[1747 9965]
.
[1730 9998]
.
[1737 9995]
.
[1702 9976]
.
[1698 9999]
.
[1750 9999]
.
[1736 9993]
.
[1733 9953]
.
[1763 9988]
.
[1694 9985]
.
[1733 9951]
.
[1756 9973]
.
[1754 9945]
.
[1697 9999]
.
[1813 9907]
.
[1701 9979]
.
[1804 9918]
.
[1892 9748]
.
[1831 9882]
.
[1688 9979]
.
[1720 9957]
.
[1808 9910]
.
[1787 9917]
.
[1770 9954]
.
[1756 9946]
.
[1753 9944]
.
[1808 9890]
.
[1767 9924]
.
[1846 9806]
.
[1880 9773]
.
[1924 9728]
.
[1722 9966]
.
[1749 9952]
.
[1728 9906]
.
[1709 9985]
.
[1725 9983]
.
[2212 9283]
.
[1866 9804]
.
[2591 8745]
.
[1697 9933]
..
[1888 9816]
.
[1720 9975]
.
[1843 9810]
.
[1776 9929]
.
[1727 9993]
.
[1745 9968]
.
[2018 9555]
.
[2185 9353]
.
[1802 9848]
.
[1898 9693]
...
[2210 9312]
.....
[2609 8723]
.
[2904 8418]
.
[2393 8984]
.
[2642 8708]
.
[2573 8833]
.......
[2827 8481]
..
[2958 8369]
......
[2061 9519]
......
[3131 8044]
....
[2985 8259]
...............................
[3286 7930]
.......................
[3986 7051]
.........
[7778 3052]
.........
[4519 6472]
..........
[5119 5761]
......
[5212 5656]
............
[4548 6428]
.....
[7214 3481]
....................................................................................................................................................................................................................
Data Dump...

Data Dump...
..
Data Dump...
..
Data Dump...
..................
Data Dump...
..............................................................................................................................................
[  76 7102]
..........
[  78 6739]
................
[  78 6734]
...................
[ 109 6432]
.............
[  87 6205]
............
[ 109 5913]
...
[ 133 5560]
....
[ 124 5784]
......
[ 108 5900]
....
[ 103 6216]
........
[ 114 5796]
....
[ 107 5886]
.......
[ 123 5769]
....
[  99 6037]
..
[ 130 5703]
....
[ 144 5449]
.
[ 118 5737]
...
[ 136 5416]
....
[ 134 5474]
.
[ 149 5404]
...
[ 175 5152]
.
[ 167 5289]
........
[ 200 5170]
.
[ 154 5008]
...
[ 205 4863]
........
[ 223 4690]
..
[ 190 4940]
....
[ 182 5132]
.
[ 166 4942]
.
[ 232 4936]
..
[ 190 4859]
............
[ 209 5036]
..
[ 222 4689]
.
[ 241 4641]
..
[ 235 4791]
.
[ 201 4977]
......
[ 199 4628]
....
[ 224 4553]
................
[ 291 4238]
.....
[ 335 3666]
..........
[ 337 3732]
.........
[ 376 3745]
........
[ 394 3725]
.......
[ 397 3830]
......................
[ 534 3116]
..
[ 457 3461]
..
[ 457 3641]
...
[ 542 2986]
.............................
[ 593 2870]
....
[ 557 3186]
.....
[ 895 2182]
................
[ 563 3413]
.
[1040 1849]
.......................
[ 773 2669]
....
[ 796 2789]
...
[ 952 2173]
..............
[1009 1959]
......
[1242 1608]
..
[ 643 2782]
...
[1198 1706]
.......
[3135  182]
...
[1090 1976]
...
[ 992 2376]
.
[1018 2109]
...........................................
[3005  126]
...........................
[1751 1202]
..............
[2201  512]
.
[2172  700]
.
[1414 1519]
.......
[1719 1173]
.............................................................................................
[ 54 865]
...................
[ 45 784]
..................
[ 50 833]
.............................
[ 63 728]
...............................
[ 40 588]
..............................
[ 66 355]
....
[ 61 381]
...
[ 45 625]
...........
[ 57 304]
...................
[ 58 657]
....
[ 44 626]
.
[ 44 689]
.
[ 54 478]
.....
[ 60 439]
.......
[ 71 376]
.....
[ 62 379]
...............
[ 58 385]
..
[ 59 409]
........
[ 63 379]
..
[ 62 475]
..
[ 68 436]
...
[ 78 484]
..................
[ 69 226]
.......
[ 81 333]
..
[ 85 158]
........
[ 84 109]
....
[ 77 254]
..
[ 82 458]
.......
[ 61 186]
............
[ 86 313]
.
[ 74 448]
...
[ 59 234]
.
[ 67 347]
....
[ 76 219]
..
[ 62 200]
.............
[ 91 131]
.
[ 62 185]
...............
[ 93 104]
.........................
[88 33]
..........
[83 87]
.....................
[93 77]
...
[73 42]
.
[101  77]
.....................
[109  74]
.....
Data Dump...
........................
[92 70]
..
Data Dump...
...
[117  34]
..........
[ 88 138]
.........
[107  15]
...
Data Dump...
..................................
[122  11]
.
Data Dump...
..
[99 10]
......................
[104 190]
............
[120  14]
.........
[102  67]
.......
Data Dump...
..............................
[83 46]
.
Data Dump...
........
[113  91]
.......
Data Dump...

Data Dump...
..
[123  23]
......
[120  19]
..........
[101   6]
....
[161  11]
.
Data Dump...
.......
[127  15]
.............
[100  95]
..
Data Dump...
..
Data Dump...
.
[108  38]
.....
[122  20]
.
Data Dump...
.
Data Dump...
....
Data Dump...
..
Data Dump...
.................
Data Dump...
............
Data Dump...
...
Data Dump...
...
Data Dump...
..
Data Dump...

Data Dump...
.
Data Dump...
....
[177   8]
.........................
[131  21]
.
Data Dump...

Data Dump...

Data Dump...
..........
[90 16]
.....
Data Dump...
..
[144   7]
....
Data Dump...

Data Dump...
.
[132  14]
........
Data Dump...

Data Dump...
..
Data Dump...

Data Dump...
...
[115  28]
..
[116  34]
..
Data Dump...
...
Data Dump...

Data Dump...
..........
Data Dump...
.
Data Dump...
..........
Data Dump...
.................
Data Dump...
...
Data Dump...
...........
Data Dump...

Data Dump...

Data Dump...
............
Data Dump...
.................
Data Dump...

Data Dump...
....
Data Dump...

Data Dump...
.....................
Data Dump...
.
Data Dump...
.......
Data Dump...
.......
Data Dump...
.
Data Dump...
................
Data Dump...
.
Data Dump...
..
Data Dump...
.
Data Dump...
....
Data Dump...

Data Dump...
.
Data Dump...
...
Data Dump...
.
Data Dump...

Data Dump...
........
Data Dump...
....
Data Dump...
..
Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...

Data Dump...
Low 1 0
Done
slurmstepd-phcompute025: error: Detected 18 oom-kill event(s) in StepId=824565.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
