Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367758): Gdk-CRITICAL **: 09:29:55.492: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367760): Gdk-CRITICAL **: 09:29:55.544: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367768): Gdk-CRITICAL **: 09:29:55.593: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367779): Gdk-CRITICAL **: 09:29:55.638: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367777): Gdk-CRITICAL **: 09:29:55.647: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367793): Gdk-CRITICAL **: 09:29:55.691: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367789): Gdk-CRITICAL **: 09:29:55.725: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367797): Gdk-CRITICAL **: 09:29:55.813: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367803): Gdk-CRITICAL **: 09:29:55.822: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3367807): Gdk-CRITICAL **: 09:29:55.898: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4706 9992]
.
[4748 9961]
.
[4656 9999]
.
[4664 9994]
.
[4678 9941]
.
[4681 9973]
.
[4699 9944]
.
[4801 9718]
.
[4908 9618]
................................................................................
[2234 9978]
..
[2204 9999]
.
[2177 9987]
.
[2351 9780]
..
[2187 9892]
.
[2269 9650]
.
[2438 9566]
.....
[2680 8180]
..
[2602 8525]
.....................................................................
[1108 9940]
.
[1126 9999]
..
[1098 9971]
..
[1083 9646]
...
[1214 9319]
......
[1230 8788]
....
[1388 8208]
..................
[1602 6793]
.....
[1855 5659]
..................................
[ 594 9999]
.
[ 582 9857]
.....
[ 585 9917]
......
[ 591 9147]
..........
[ 702 8190]
.............
[ 795 6941]
.............
[ 911 5892]
........................
[ 319 9999]
..
[ 333 9616]
.
[ 341 9777]
...
[1075 4930]
...............
[1420 3532]
..
[ 352 8134]
......................
[ 465 6488]
..............
[ 193 9999]
...........
[ 197 9199]
...
[ 210 8903]
..
[ 574 4841]
.........................
[ 690 3818]
...........
[ 125 9999]
..
[ 240 6574]
...................
[ 781 3346]
...........
[ 135 7779]
.....
[ 146 7536]
....
[ 347 4679]
.
[1136 2168]
.....
[  91 9999]
.....................................
[ 455 3124]
.....
[  72 9999]
..........
[ 182 4915]
.............
[ 110 5705]
...
[ 546 2411]
.......
[ 112 5721]
..
[  60 9999]
.........................
[ 608 2261]
....
[  51 9999]
...
[ 290 3160]
.....................
[  43 9999]
..........
[ 920 1290]
..........
[  41 9999]
...../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[ 147 3425]
..
[  88 3776]
...
[ 362 1996]
....
[  92 3944]
........................
[ 443 1474]
.............
[ 228 2074]
.......
[ 487 1502]
...................
[  76 2420]
.
[ 118 2317]
..
[  78 2565]
.
[754 788]
...............
[ 293 1270]
.............................
[371 904]
.......
[ 201 1355]
............
[ 394 1004]
...
[  73 1552]
...
[  69 1674]
..
[ 100 1521]
.....................
[621 504]
...........
[243 823]
.............................
[164 870]
..
[320 597]
..
[  68 1019]
..
[  57 1122]
.......
[ 87 971]
....
[316 688]
....................................
[545 341]
.....
[205 530]
...............
[ 51 739]
...
[ 61 679]
....
[139 593]
.....
[ 75 671]
......
[268 393]
..............
[269 471]
...............................
[ 49 523]
.........
[ 58 461]
.
[181 365]
..
[455 212]
.........
[ 63 457]
....
[118 415]
..........................
[230 255]
........
[226 338]
.....
[ 44 350]
...........
[ 53 308]
................
[ 60 321]
.........
[159 248]
......
[105 297]
......
[391 137]
..............
[ 39 245]
................
[ 51 227]
......
[195 175]
..
[192 255]
.........
[ 54 242]
...........................
[ 38 175]
.
[ 98 228]
......
[137 179]
...............
[ 50 174]
.......
[327  91]
...........
[ 51 198]
..................
[ 36 128]
.
[167 174]
....
[169 131]
...................
[ 86 177]
....
[ 46 126]
.................
[116 125]
......
[ 44 151]
....
[ 34 108]
.............................
[282  74]
........
[ 45 100]
........
[146 140]
.....
[32 88]
.
[ 79 133]
.........
[145  95]
.
[ 42 121]
.................................
[100  94]
...
[31 70]
..
[43 81]
............................
[ 41 105]
.........
[31 60]
......
[ 75 103]
...........
[241  53]
..
[129 105]
.......
[40 64]
..........
[30 54]
................
[120  70]
.......
[34 88]
........
[30 51]
...............
[90 69]
..........
[39 56]
.
[30 50]
.../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[70 77]
.............
[33 78]
................
[37 51]
....
[111  86]
...................
[204  38]
.....
[32 68]
..........
[37 41]
........
[113  54]
....
[65 67]
.......
[83 55]
...........
[30 64]
.
[37 39]
..............................
[37 39]
......
[30 57]
.............
[98 73]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...........
[30 57]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...

[63 54]
.............
[172  31]
....
[75 46]
....
[100  44]
...............
[60 47]
...
[89 61]
.............................
[57 42]
.
[70 36]
...........
[137  25]
...
[92 35]
.........
[81 51]
.......
[56 40]
.........................
[62 29]
....
[54 36]
.................
[75 46]
......
[84 29]
...
[51 35]
.
[125  19]
......................
[51 34]
........
[57 25]
............
[48 34]
..........
[70 44]
........
[48 33]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
........
[75 22]
...........
[106  16]
.
[50 23]
.......
[64 37]
...........................
[69 20]
...
[48 21]
.
[58 33]
..............
[98 15]
...............
[54 28]
.....
[45 21]
............
[64 15]
.............
[50 24]
..........
[39 21]
..
[88 15]
...............
[47 24]
..............
[59 12]
.....
[38 20]
.....
[45 23]
.....................
[45 23]
.............
[78 12]
..
[34 19]
.....
[45 23]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
......
[55 12]
.......
[32 17]
..................
[31 16]
.............
[73 12]
...
[52 11]
.
[31 16]
................
[31 16]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.........
[49 11]
....
[65  9]
.............
[45 11]
...........
[62  9]
......
[44  8]
................
[43  8]
....
[57  9]
............
[42  8]
...............
[40  8]
.
[53  9]
..............
[40  8]
..............
[40  7]
....
[50  8]
..........
[40  7]
............./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[40  7]

Data Dump...
....
[46  8]
..........
[45  7]
..........
[42  7]
..........
[41  7]
..........
[40  7]
..........
[40  7]
..........
[40  7]
..........
[39  7]
..........
[39  7]
..........
[39  7]
./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
Low 1 0
Done
